### ISSUE TITLE
Neural Network expression is empty

### ISSUE THREAD

**Issue by Nicolaj-Becker** [Artelnics/opennn#146] opened 2020-08-07 09:28 UTC
Hello,

I just started working with your library and ran into a problem.

My installation is a Ubuntu 18.04 with QT creator. I cloned and compiled and everything looks fine.
When I run the examples e.g. simple_function_regression termimal opens and progress is shown but after completion the expression.txt is empty. 
I tried save_expression_python as well. There is function written to the file but no calculations in it.

```
#!/usr/bin/python

def expression(inputs) : 

    if type(inputs) != list:
       print('Argument must be a list')
       exit()
    if len(inputs) != 2:
       print('Incorrect number of inputs')
       exit()
    x1=inputs[0]
    x2=inputs[1]
    
    return y 
```

Hope you can help.

Thnx
Nico

**Comment by alessandrobrando** [comment] 2020-08-20 16:17
While the problem isn't solved , you can use the write_expression () function for each layer of your network. Also, note that when saving your network in XML, you have access to the weights and bias.

**Comment by jandres-artelnics** [comment] 2020-08-31 10:15
Hi @Nicolaj-Becker and @alessandrobrando .

This issue is now fixed in dev branch.

You can check this on some examples, for instance: "urinary_inflammations_diagnosis" example.

I close the issue. If something goes wrong please feel free to open an issue. 

Thank you.

**Closed by jandres-artelnics** 2020-08-31 10:15 UTC
