### ISSUE TITLE
GPU Driving Training

### ISSUE THREAD

**Issue by kevinchahine** [Artelnics/opennn#223] opened 2022-04-21 11:34 UTC
How can I make OpenNN use a GPU when training? When I train using OpenNN, all the work is done on the CPU instead. Does OpenNN automatically select a GPU device to train on or does a GPU need to be selected from the code.

**Comment by davidge807** [comment] 2022-04-25 09:12
Duplicate of #214

**Closed by davidge807** 2022-04-25 09:12 UTC
