### ISSUE TITLE
PerformanceFunctional

### ISSUE THREAD

**Issue by TrifonT** [Artelnics/OpenNN#38] opened 2017-10-28 14:32 UTC
PerformanceFunctional type found in file informedness_optimization_threshold.cpp is not declared anywhere.

**Comment by BrainStone** [comment] 2018-06-21 03:40
I'm having this issue too!

Both gcc and VisualStudio are complaining about this. Would a compilation log help?

**Comment by BrainStone** [comment] 2018-06-21 11:36
Another thing I discovered is that file isn't even compiled when using cmake. So it could be deleted.

@TrifonT I'm assuming you also just set your build chain to compile all sources. You can savely ignore this file.

**Comment by TrifonT** [comment] 2018-06-22 09:00
@BrainStone  thanks for comments and info. 
Anyway I quit trying using this project some time ago.

**Comment by RoberLopez** [comment] 2018-12-31 11:42
Sorry about that. The problem is fixed now.

**Closed by RoberLopez** 2018-12-31 11:42 UTC
