### ISSUE TITLE
cmake compile error

### ISSUE THREAD

**Issue by TonyXiong0** [Artelnics/opennn#231] opened 2022-08-13 14:14 UTC
I'm using a 16" M1 chip MacBook using cmake . When compiling, I encountered the following error
![截屏2022-08-13 22 13 36](https://user-images.githubusercontent.com/96694051/184498014-e2f5580b-3852-4baf-93c5-a8e7ae68faf2.png)
Is there any way to fix it?

**Comment by davidge807** [comment] 2022-08-16 09:30
Duplicate of #230

**Closed by davidge807** 2022-08-16 09:30 UTC
